"""routelens CLI.

    routelens install --config config.yaml [--patch]   wire RouteLens into a LiteLLM proxy
    routelens demo [--serve]                            generate sample multi-turn sessions
    routelens serve --db routelens.db                   run the dashboard standalone
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
from pathlib import Path

SHIM_NAME = "routelens_callback"
SHIM = '''"""Generated by `routelens install`.

LiteLLM loads callbacks from a .py file next to the proxy config (it does not
import installed packages), so this file re-exports RouteLens for it.
"""
from routelens import instance  # noqa: F401
'''
CALLBACK_REF = SHIM_NAME + ".instance"


def _install(config: str, patch: bool) -> None:
    cfg = Path(config).resolve()
    if not cfg.exists():
        sys.exit("Config file not found: %s" % cfg)
    shim = cfg.parent / (SHIM_NAME + ".py")
    if not shim.exists() or shim.read_text() != SHIM:
        shim.write_text(SHIM)
    print("Wrote %s" % shim)

    text = cfg.read_text()
    if CALLBACK_REF in text:
        print("%s already references %s. Nothing to change." % (cfg.name, CALLBACK_REF))
        return

    manual = ("Add this to %s:\n\n  litellm_settings:\n    callbacks: %s\n\n"
              "(if you already have a `callbacks:` list, append %s to it)" % (cfg.name, CALLBACK_REF, CALLBACK_REF))
    if not patch:
        print(manual)
        print("\nOr re-run with --patch to edit the file for you (a .bak copy is kept).")
        return

    lines = text.splitlines()
    head = next((i for i, l in enumerate(lines) if re.match(r"^litellm_settings\s*:\s*(#.*)?$", l)), None)
    if head is None:
        new = text.rstrip("\n") + "\n\nlitellm_settings:\n  callbacks: %s\n" % CALLBACK_REF
    else:
        block_end = next((i for i in range(head + 1, len(lines)) if lines[i].strip() and not lines[i].startswith((" ", "\t", "#"))), len(lines))
        if any(re.match(r"^\s+callbacks\s*:", l) for l in lines[head + 1:block_end]):
            print("`litellm_settings.callbacks` already exists, so I won't guess how to merge.\n" + manual)
            return
        nxt = next((l for l in lines[head + 1:block_end] if l.strip() and not l.lstrip().startswith("#")), "  x")
        indent = nxt[: len(nxt) - len(nxt.lstrip())] or "  "
        lines.insert(head + 1, "%scallbacks: %s" % (indent, CALLBACK_REF))
        new = "\n".join(lines) + "\n"
    shutil.copyfile(cfg, str(cfg) + ".bak")
    cfg.write_text(new)
    print("Patched %s (backup: %s.bak). Restart the proxy, then open /routelens." % (cfg.name, cfg.name))


def _serve(db: str, host: str, port: int) -> None:
    try:
        import uvicorn
        from fastapi import FastAPI
    except ImportError:
        sys.exit("`routelens serve` needs fastapi and uvicorn (pip install 'litellm[proxy]').")
    from fastapi.responses import RedirectResponse

    from .api import build_router
    from .store import Store

    app = FastAPI(title="RouteLens", docs_url=None, redoc_url=None)
    app.include_router(build_router(Store(db)))

    @app.get("/", include_in_schema=False)
    async def root():  # noqa: ANN202
        return RedirectResponse("/routelens")

    print("RouteLens dashboard: http://%s:%d/routelens" % ("localhost" if host == "0.0.0.0" else host, port))
    uvicorn.run(app, host=host, port=port, log_level="warning")


def main(argv: "list[str] | None" = None) -> None:
    p = argparse.ArgumentParser(prog="routelens")
    sub = p.add_subparsers(dest="cmd", required=True)

    ins = sub.add_parser("install", help="add RouteLens to a LiteLLM proxy config")
    ins.add_argument("--config", default="config.yaml")
    ins.add_argument("--patch", action="store_true", help="edit the config file instead of printing instructions")

    for name, help_ in (("serve", "run the dashboard against an existing routelens DB"),
                        ("demo", "generate sample multi-turn sessions")):
        sp = sub.add_parser(name, help=help_)
        sp.add_argument("--db", default=os.environ.get("ROUTELENS_DB", "routelens.db"))
        sp.add_argument("--host", default="127.0.0.1")
        sp.add_argument("--port", type=int, default=8787)
        if name == "demo":
            sp.add_argument("--serve", action="store_true", help="start the dashboard after seeding")
    args = p.parse_args(argv)

    if args.cmd == "install":
        _install(args.config, args.patch)
        return
    if args.cmd == "demo":
        from .demo import generate
        from .store import Store
        store = Store(args.db)
        count = generate(store)
        store.flush()
        print("Wrote %d demo attempts to %s" % (count, args.db))
        if not args.serve:
            return
    _serve(args.db, args.host, args.port)


if __name__ == "__main__":
    main()
