"""Generated by `routelens install`.

LiteLLM loads callbacks from a .py file next to the proxy config (it does not
import installed packages), so this file re-exports RouteLens for it.
"""
from routelens import instance  # noqa: F401
